apiVersion: v1
kind: Service
metadata:
  name: fxtrader-http-service
spec:
  selector:
    app: fxtrader
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
    nodePort: 30100
  type: NodePort