apiVersion: v1
kind: Service
metadata:
  name: fxtrader-service
  namespace: fxtrader
spec:
  selector:
    app: fxtrader
  ports:
  - name: http
    protocol: TCP
    port: 7000
    targetPort: 7000
    nodePort: 30100
  - name: websocket
    protocol: TCP
    port: 7003
    targetPort: 7003
    nodePort: 30101
  type: NodePort