apiVersion: v1
kind: ConfigMap
metadata:
  name: fxtrader-config
  namespace: fxtrader
data:
  ADDRESS: "0.0.0.0"
  PORT: "8080"
  BASE_URL: "http://fxtrader-service.fxtrader.svc.cluster.local:8080"
  MT5_HOST: "mt5-mock.fxtrader.svc.cluster.local"
  MT5_PORT: "5000"
  LISTEN_PORT: "5001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fxtrader-config
  namespace: fxtrader
data:
  ADDRESS: 0.0.0.0
  BASE_URL: http://fxtrader-service.fxtrader.svc.cluster.local:8080
  LISTEN_PORT: "5001"
  MT5_HOST: mt5-mock.fxtrader.svc.cluster.local
  MT5_PORT: "5000"
  PORT: "8080"
  MONGO_URI: mongodb://mongodb-0.mongodb.fxtrader.svc.cluster.local:27017/fxtrader