apiVersion: v1
kind: Secret
metadata:
  name: fxtrader-secret
  namespace: fxtrader
type: Opaque
stringData:
  PORT: "7000"
  ADDRESS: "0.0.0.0"
  BASE_URL: "http://localhost:7001"
  MONGO_URI: "mongodb://mongodb-service.fxtrader:27017/?authSource=admin"
  ADMIN_USER: "admin"
  ADMIN_PASS: "admin"
  JWT_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"
  LISTEN_PORT: "7003"