apiVersion: v1
kind: Secret
metadata:
  name: fxtrader-secret
  namespace: fxtrader
type: Opaque
stringData:
  ADDRESS: "0.0.0.0"
  ADMIN_USER: "admin"
  ADMIN_PASS: "admin"
  JWT_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM"
  LISTEN_PORT: "7003"
  MONGO_URI: "mongodb://admin:admin@mongodb-service.fxtrader:27017/fxtrader?authSource=admin"
  PORT: "7000"
  BOT_TOKEN: BOT_TOKEN
